export default async function handler(req,res){
 const input=req.method==='GET'?(req.query||{}):(req.body||{});
 if(req.method!=='GET'&&req.method!=='POST') return res.status(405).json({error:'Method not allowed'});
 const defaultPrompt=`Buat video vertikal 9:16 berdurasi tepat 50 detik, terdiri dari 5 scene masing-masing 10 detik, tentang karakter antropomorfik berupa processor komputer modern. Bentuk utamanya tetap jelas seperti CPU persegi kecil dengan heat spreader metalik silver dan kontak/pin kecil berwarna keemasan. Wajah kartun 3D ekspresif menyatu natural pada processor. Scene 1: CPU berada di motherboard dan awalnya tenang, lalu banyak proses kerja datang dan CPU mulai kesal. Scene 2: beban kerja semakin berat, CPU semakin panas, kipas berputar cepat, CPU terlihat frustrasi. Scene 3: CPU kehilangan kesabaran, sangat marah, panas dan sedikit uap muncul, motherboard bergetar ringan secara komedi. Scene 4: CPU melihat langsung ke kamera dan memarahi pengguna karena memberi beban kerja terlalu berat, ekspresi sangat lucu dan dramatis. Scene 5: pekerjaan selesai, CPU kelelahan dan pasrah, kipas kembali normal, kamera perlahan zoom out untuk ending komedi. Gunakan animasi 3D cinematic berkualitas tinggi, detail hardware realistis, karakter konsisten di semua scene, ekspresi wajah berlebihan namun lucu, gerakan kamera halus, pencahayaan dramatis, polished animation. Gunakan narasi bahasa Indonesia oleh suara pria dewasa yang hangat dan jelas dengan tempo sedang. Jangan tampilkan subtitle, teks di layar, logo, atau watermark.`;
 const prompt=(input.prompt?.trim()||((req.method==='GET')?defaultPrompt:''));
 const duration=input.duration||50;
 if(!prompt) return res.status(400).json({error:'Prompt wajib diisi'});
 const baseUrl='https://agnes-dockerhub-production.up.railway.app';
 const apiKey=process.env.AGNES_API_KEY;
 if(!apiKey) return res.status(503).json({error:'AGNES_API_KEY belum diset di Vercel'});
 try{
  const seconds=Number(duration)||50;
  if(seconds<2||seconds>150) return res.status(400).json({error:'Duration harus 2-150 detik'});
  const sceneCount=Math.ceil(seconds/10);
  const base=Math.floor(seconds/sceneCount), rem=seconds%sceneCount;
  const durations=Array.from({length:sceneCount},(_,i)=>base+(i<rem?1:0));
  const form=new FormData();
  form.append('idea',prompt);
  form.append('creative_name','ChatGPT Agnes Long Video');
  form.append('style','premium cinematic 3D animation, consistent character design, smooth camera movement, expressive cartoon character, polished animation');
  form.append('chaining_mode','keyframes');
  form.append('video_width','1080');
  form.append('video_height','1920');
  form.append('duration_source','manual');
  form.append('scene_count',String(sceneCount));
  form.append('uniform_duration','false');
  form.append('scene_durations_json',JSON.stringify(durations));
  form.append('audio_enabled','true');
  form.append('audio_voice','id-ID-ArdiNeural');
  form.append('audio_rate','+0%');
  form.append('audio_lang','id-ID');
  form.append('subtitle_enabled','false');
  const r=await fetch(`${baseUrl}/api/tasks/creative`,{method:'POST',headers:{Authorization:`Bearer ${apiKey}`},body:form});
  const text=await r.text(); let data; try{data=JSON.parse(text)}catch{data={message:text}};
  if(!r.ok)return res.status(r.status).json({error:data.detail||data.error||data.message||'Agnes API error',details:data});
  const taskId=data.task_id||data.taskId||data.id;
  if(!taskId)return res.status(502).json({error:'Agnes tidak mengembalikan task ID',details:data});
  return res.status(200).json({taskId,status:data.status||'pending',duration:seconds,sceneCount,durations,autoGenerated:req.method==='GET'&&!input.prompt});
 }catch(e){return res.status(500).json({error:e.message||'Request gagal'});}
}
